{{- if .Values.podDisruptionBudget.create }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: jspolicy
  labels:
    app: {{ template "jspolicy.fullname" . }}
    release: {{ .Release.Name }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "jspolicy.fullname" . }}
      release: {{ .Release.Name }}
{{- end }}